// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwOZT8djrXAYsP95o5QA_jISp8URfNS0',
    appId: '1:460542692785:web:06c21d905e010aca7c8190',
    messagingSenderId: '460542692785',
    projectId: 'cattle-guru-60a54',
    authDomain: 'cattle-guru-60a54.firebaseapp.com',
    storageBucket: 'cattle-guru-60a54.appspot.com',
    measurementId: 'G-1E2NR9CYMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMcgj5pTlOKxeStexIZH5mwpyoOjenr4',
    appId: '1:460542692785:android:53255b7eab9052b87c8190',
    messagingSenderId: '460542692785',
    projectId: 'cattle-guru-60a54',
    storageBucket: 'cattle-guru-60a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD32NKR-WuzsgbeagZGaQ8f_FJSj3dU0a8',
    appId: '1:460542692785:ios:c8a44e009205be4c7c8190',
    messagingSenderId: '460542692785',
    projectId: 'cattle-guru-60a54',
    storageBucket: 'cattle-guru-60a54.appspot.com',
    androidClientId: '460542692785-1agrf30kgvn4dttonlot3jj6q222mvb4.apps.googleusercontent.com',
    iosClientId: '460542692785-4lo5nnbq6jesc0tdf0qsd9eebv90detd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleGuru',
  );
}
